op {
  name: "ExperimentalFunctionBufferingResource"
  input_arg {
    name: "string_arg"
    type: DT_STRING
  }
  input_arg {
    name: "target_device"
    type: DT_STRING
  }
  output_arg {
    name: "resource"
    type: DT_RESOURCE
  }
  attr {
    name: "shared_name"
    type: "string"
  }
  attr {
    name: "container"
    type: "string"
  }
  attr {
    name: "f"
    type: "func"
  }
  attr {
    name: "buffer_size"
    type: "int"
  }
  attr {
    name: "output_types"
    type: "list(type)"
  }
  is_stateful: true
}
op {
  name: "ExperimentalFunctionBufferingResourceGetNext"
  input_arg {
    name: "function_buffer_resource"
    type: DT_RESOURCE
  }
  output_arg {
    name: "output"
    type_list_attr: "output_types"
  }
  attr {
    name: "output_types"
    type: "list(type)"
    has_minimum: true
    minimum: 1
  }
  is_stateful: true
}
op {
  name: "ExperimentalFunctionBufferingResourceReset"
  input_arg {
    name: "function_buffer_resource"
    type: DT_RESOURCE
  }
  is_stateful: true
}